name: Sage IQ
markdown: redcarpet
highlighter: true
title: Sage IQ
email: info@sage-iq.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: /
exclude: [README.md, makefile]

google_analytics_tracking_id: UA-77677545-1